### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by jrootham** [CivicTechTO/budgetpedia-frontend#1]
Convert build process from Gulp to webpack.

**Comment by bastienvinh** [comment]
I think with can combine the two of them. We need webpack for sure. But I use VScode also. And gulp is used by the editor to launch task.

This is a little example of what you can do. [Example](https://github.com/bastienvinh/template-vue-webpack/blob/master/gulpfile.js). It's very light but at least it is one way to do.

I would like to use gulp as an entry point if possible but using webpack at the same time.

**Comment by HenrikBechmann** [comment]
@bastienvinh Yes please!

**Comment by HenrikBechmann** [comment]
I've switched to webpack. gulp not necessary right now, but can add later if needed.
