### ISSUE TITLE
Animation for Hide / Show components with explorer

### ISSUE THREAD

**Issue by bastienvinh** [CivicTechTO/budgetpedia-frontend#4]
Link : [Explorer](http://budgetpedia.ca/explorer)

When we use the show/hide options like this one : 
![elements](https://user-images.githubusercontent.com/5178193/32511836-0b67bc1a-c3c3-11e7-8ac7-7a746e080726.png)

Then you have kind of fast event that hides the element but for a user perspective, it is to violent for the eyes. Especially if the eyes doesn't recognize the structure because the position has completely changed somehow.

**Comment by HenrikBechmann** [comment]
Agreed!

**Comment by HenrikBechmann** [comment]
Done!
